server:
  servlet:
    context-path: /api

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"